services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: wikiracer
      POSTGRES_PASSWORD: wikiracer
      POSTGRES_DB: wikiracer
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - proxy

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    volumes:
      - redis_data:/data
    networks:
      - proxy

  server:
    build:
      context: ./
      dockerfile: server/Dockerfile
    restart: unless-stopped
    env_file:
      - ./server/.env.local
    depends_on:
      - redis
      - postgres
    networks:
      - proxy

  client:
    build:
      context: ./
      dockerfile: client/Dockerfile
      args:
        NEXT_PUBLIC_SERVER_URL: https://api.wikiracer.enzogarnier.fr
    restart: unless-stopped
    env_file:
      - ./client/.env
    networks:
      - proxy

volumes:
  redis_data:
  postgres_data:

networks:
  proxy:
    external: true